export const buttonsData = [
  {
    category: "Programming",
    buttons: [
      { label: "Python", icon: "devicon-python-plain", type: "Python" },
      { label: "JavaScript", icon: "devicon-javascript-plain", type: "JavaScript" },
      { label: "TypeScript", icon: "devicon-typescript-plain", type: "TypeScript" },
      { label: "Java", icon: "devicon-java-plain", type: "Java" },
      { label: "Go", icon: "devicon-go-plain", type: "Go" },
      { label: "Kotlin", icon: "devicon-kotlin-plain", type: "Kotlin" },
      { label: "C", icon: "devicon-c-plain", type: "C" },
      { label: "C++", icon: "devicon-cplusplus-plain", type: "Cpp" },
      { label: "C#", icon: "devicon-csharp-plain", type: "Csharp" },
      { label: "PHP", icon: "devicon-php-plain", type: "PHP" },
      { label: "Rust", icon: "devicon-rust-plain", type: "Rust" },
      { label: "Haskell", icon: "devicon-haskell-plain", type: "Haskell" },
      { label: "Ruby", icon: "devicon-ruby-plain", type: "Ruby" },
      { label: "Elixir", icon: "devicon-elixir-plain", type: "Elixir" },
      { label: "Clojure", icon: "devicon-clojure-plain", type: "Clojure" },
      { label: "Scala", icon: "devicon-scala-plain", type: "Scala" },
      { label: "Swift", icon: "devicon-swift-plain", type: "Swift" },
      { label: "Bash", icon: "devicon-bash-plain", type: "Bash" },
      { label: "Lua", icon: "devicon-lua-plain", type: "Lua" },
      { label: "Perl", icon: "devicon-perl-plain", type: "Perl" },
      { label: "R", icon: "devicon-r-plain", type: "R" },
      { label: "Dart", icon: "devicon-dart-plain", type: "Dart" },
      { label: "Elm", icon: "devicon-elm-plain", type: "Elm" },
      { label: "F#", icon: "devicon-fsharp-plain", type: "FSharp" },
      { label: "Objective-C", icon: "devicon-objectivec-plain", type: "ObjectiveC" },
      { label: "Julia", icon: "devicon-julia-plain", type: "Julia" },
      { label: "Prolog", icon: "devicon-prolog-plain", type: "Prolog" },
      { label: "MATLAB", icon: "devicon-matlab-plain", type: "Matlab" },
      { label: "Assembly", icon: "devicon-labview-plain", type: "Assembly" },
      { label: "SQL", icon: "devicon-azuresqldatabase-plain", type: "SQL" },
      { label: "Shell", icon: "devicon-bash-plain", type: "Shell" },
    ],
  },
];
