export const buttonsData = [
  {
    category: "Programming",
    buttons: [
      { label: "Python", icon: "devicon-python-plain", type: "Python" },
      { label: "JavaScript", icon: "devicon-javascript-plain", type: "JavaScript" },
      { label: "TypeScript", icon: "devicon-typescript-plain", type: "typescript" },
      { label: "Java", icon: "devicon-java-plain", type: "Java" },
      { label: "Go", icon: "devicon-go-plain", type: "Go" },
      { label: "Kotlin", icon: "devicon-kotlin-plain", type: "Kotlin" },
      { label: "C", icon: "devicon-c-plain", type: "C" },
      { label: "C++", icon: "devicon-cplusplus-plain", type: "Cpp" },
      { label: "C#", icon: "devicon-csharp-plain", type: "Csharp" },
      { label: "PHP", icon: "devicon-php-plain", type: "PHP" },
      { label: "Rust", icon: "devicon-rust-plain", type: "Rust" },
      { label: "Haskell", icon: "devicon-haskell-plain", type: "Haskell" },
      { label: "Ruby", icon: "devicon-ruby-plain", type: "Ruby" },
      { label: "Elixir", icon: "devicon-elixir-plain", type: "Elixir" },
      { label: "Clojure", icon: "devicon-clojure-plain", type: "Clojure" },
      { label: "Scala", icon: "devicon-scala-plain", type: "Scala" },
      { label: "Swift", icon: "devicon-swift-plain", type: "Swift" },
      { label: "Bash", icon: "devicon-bash-plain", type: "Bash" },
    ],
  },
];